IDK what i am doing. Someone PR if know how to fix circular import errors
/app/.heroku/python/bin/python3: Error while finding module specification for 'Himawari.main' (ImportError: cannot import name 'DB_URL' from partially initialized module 'Himawari' (most likely due to a circular import) (/app/Himawari/__init__.py))

Signed-off-by: Arsh <87128542+ArshCypherZ@users.noreply.github.com>